kind: PersistentVolume
apiVersion: v1
metadata:
  name: cockroach-pv-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /cockroachdata/pv-1
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cockroach-pv-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /cockroachdata/pv-2
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cockroach-pv-3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /cockroachdata/pv-3
